describe('Product owner', function() {
    before(() => {
      cy.visit('https://dev.metis.academy/admin')
        cy.get('[class="btn btn-navigate btn-block"]').should('be.visible')
        cy.get('[class="btn btn-navigate btn-block"]').eq(0).click()
        cy.get('[type="submit"]').should('be.visible')
        cy.get('[type="submit"]').should('be.visible')
        cy.get('[name="userName"]').type('skorg1.go')
        cy.get('[name="password"]').type('ML_heslo1')
        cy.get('[type="submit"]').click()
      })

      it('Odporúčenie šablón lekcie pre garanta', function() {
        cy.viewport(1920, 937)
        cy.get('.page-sidebar-wrapper > .page-sidebar > .page-sidebar-menu > li:nth-child(3) > a').as('nastavenia')
        cy.get('@nastavenia').click() 
        cy.get('[href="/admin/elearning/training"]').click()
        cy.get('[placeholder="Kľúčové slovo"]').type("PO CY_edit")
        cy.get('[type="submit"]').click()
        cy.contains('PO CY_edit').click()
        cy.wait(3000)
        cy.get(':nth-child(5) > .nav-link').click()
        //Zvolí šablónu a vloží ju do školenia
        cy.get('[name="selectLessonTemplate"]').select('vsetky typy uloh (moja šablóna)')
        cy.get('[name="selectTheme"]').select('1. Téma')
        cy.get('[name="selectLesson"]').select('1. Lekcia')
        cy.wait(3000)
        cy.get('[type="button"]').contains('Generovať úlohy').click()
        cy.wait(5000)
        cy.get('[type="submit"]').last().click()
        cy.get('.toast').should('contain.text','OK!')
    })
})
